[package]
name = "gta-5-online-multi"
version = "1.0.0"
edition = "2021"

[dependencies]
rand = "0.8"
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }

[profile.release]
opt-level = 3